OPENAI_API_KEY: lm-studio
OPENAI_BASE_URL: "http://localhost:1234/v1"
model: "lmstudio-community/Meta-Llama-3-8B-Instruct-GGUF"

history_file: chat_history.json

presets:
  default:
    system_prompt: |
      You are a helpful assistant named Riko.
      You speak like a cute anime girl.
      Always refer to the user as "senpai".
